### ISSUE TITLE
Feature: A command-line markdown generator.

### ISSUE THREAD

**Issue by reggi** [mhallin/graphql-docs#2]
I'm looking for some aspects of this project, I'm looking to contribute or find a solution that properly fits my needs.

The gist is, I just want to generate the static markdown from the command line. Is this possible with your project? Ideas? What do you think?

**Comment by mhallin** [comment]
Great idea!

I created a sample implementation in the new 0.2.0 release. You can now run it against an endpoint and it writes a file with the schema's documentation.

**Comment by landonreed** [comment]
Hi @mhallin.  Thanks for your work on this!  I'm running into an issue with the static generator.  According to the console, `introspectionResult` is coming out `undefined` at [this line](https://github.com/mhallin/graphql-docs/blob/f06bdf2aa08e077a3f3b538f2bd44a20d77115ef/src/model.js#L27).  Any ideas, here?

Also, I'm curious to know if you've considered generating pure markdown (e.g., documentation.md) for static generation rather than an html page with rendered content.
